# Generated by Django 4.0.4 on 2022-06-09 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_generales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('tipo', models.TextField(max_length=10)),
                ('comentarios', models.TextField(verbose_name=100)),
                ('autor', models.TextField(verbose_name=40)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('datos_generales_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readviews.datos_generales')),
                ('fecha_final', models.DateField()),
                ('genero', models.TextField(max_length=15)),
            ],
            bases=('readviews.datos_generales',),
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('datos_generales_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readviews.datos_generales')),
                ('plataforma', models.TextField(max_length=30)),
                ('genero', models.TextField(max_length=20)),
            ],
            bases=('readviews.datos_generales',),
        ),
        migrations.CreateModel(
            name='serie',
            fields=[
                ('datos_generales_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readviews.datos_generales')),
                ('temporadas', models.IntegerField()),
                ('plataforma', models.TextField(max_length=30)),
                ('fecha_final', models.DateField()),
            ],
            bases=('readviews.datos_generales',),
        ),
    ]
